### ISSUE TITLE
no such file to load -- activerecord

### ISSUE THREAD

**Issue by donv** [rgo/foreign_key_migrations#2]
Hi!

I am porting an application from Rails 2.3 to 3.0.  The initial require to ActiveRecord must be 

require 'active_record'

to work with Rails 3.  This will work for Rails versions back to at least 1.15.6 .

Can you please change this?  If you want, I can fork and send a pull request.

**Comment by rgo** [comment]
Thanks Donv, I'm going to change it :)

**Comment by rgo** [comment]
done
