### ISSUE TITLE
Update to work with Rails 3

### ISSUE THREAD

**Issue by donv** [rgo/foreign_key_migrations#3]
Hi!

I am porting an application using foreign_key_migrations to Rails 3, and the foreign_key_migrations gem needs a few changes to work.  I am doing the work now.  Would you like a patch with my changes?  Or maybe a fork and pull request?

I will only do what is needed for getting foreign_key_migrations to work with my applications, but I guess that will help many others.

I will keep compatibility with Rails 2 as much as possible.

**Comment by rgo** [comment]
If Rails 2 support cost a lot of effort perhaps we should have two branches (one for rails 3 and the other one for rails 2) and lost the compatibility. This plugin is enough stable for Rails 2

Create a branch to adapt it for Rails 3 could be more confortable for us. do you agree?

**Comment by donv** [comment]
Yes!  My thoughts exactly.  You create the branch?

**Comment by rgo** [comment]
rails3 branch created :)

**Comment by donv** [comment]
Excellent!  I should fork rgo/foreign_key_migrations?  What about aspgems/foreign_key_migrations?  There are unmerged changes there.  Will they be merged?

**Comment by donv** [comment]
Also, I cannot find the gemspec file.  Can you add it, please?

**Comment by donv** [comment]
More confusion:  What is the relationship with https://github.com/vigetlabs

They are listed as homepage for the foreign_key_migrations gem 0.3.0, but do not list such a repository anymore.

Also, the 0.3.0 gem has different files than the rgo repository.  Can you clarify, please?

**Comment by rgo** [comment]
These plugins (this one and redhills_core) were abandoned, I think the company closed. Then I uploaded here to have a copy because I find it very useful. 

I'm going to try to generate a gemspec file this night.

**Comment by rgo** [comment]
I merged ASPgems changes in both branches, and I added you as a collaborator

**Comment by donv** [comment]
Great!  Thanks for the confidence!

I will investigate what the differences between the source uploaded here and the gem are.  If there are significant improvements in the 0.3.0 gem, I can add them here?

**Comment by rgo** [comment]
Of course, any improvement is good :)

**Comment by donv** [comment]
The gem includes a gemspec, so you can postpone generating one, I think.

**Comment by donv** [comment]
Have you looked at the repositories at

https://github.com/mlomnicki

They seem pretty advanced.  foreign_key_migrations has been renamed to automatic_foreign_key.

**Comment by rgo** [comment]
I didn't know, perhaps we can fork it and work altogether (if needed)

**Comment by donv** [comment]
I have switched to schema_plus, so I'll close this issue.  Thanks for your effort and friendly project.
