### ISSUE TITLE
add_foreign_key arguments: gem vs plugin

### ISSUE THREAD

**Issue by donv** [rgo/foreign_key_migrations#4]
Hi!

I just upgraded our use of foreign_key_migrations from plugin (2008) to gem (0.3.0), and I see that the arguments to the add_foreign_key method have changed.  They used to be

from_table, from_colum, to_table, to_column

but now they are a hash of hashes.  ActiveRecord 3 assumes that the first argument in a schema statement is a table name, and corrupts the hash into a string.

I have added compatibility with the 4 argument method signature to our project.  Would you like this change?  I can add by patch or pull request.

**Comment by rgo** [comment]
pull request is welcome!

**Comment by donv** [comment]
Should I keep the hash way of calling the method?  I think it will not work with Rails 3.

**Comment by donv** [comment]
Switched to schema_plus, so not needed anymore.
